[package]
name = "error-stack-eyre-compat-issue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-stack = { version = "0.4.1", features = ["eyre"] }
eyre = "0.6"
thiserror = "1"
